#读写分离配置文件
server:
  port: 8080

spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      #数据源
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://IP:3306/shard-master?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: XXXX
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://IP:3306/shard-slave?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: XXXX
    # 读写分离配置
    masterslave:
      name: db-ms
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      slave-data-source-names: slave

mybatis-plus:
  mapper-locations: classpath:/mapper/* #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: com.shard.entity # 数据库表与实体类的驼峰命名自动转换
  global-config: #全局配置
    db-config:
      id-type: ID_WORKER  #主键类型  0:数据库ID自增, 1:用户输入ID, 2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID;
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.shard: DEBUG